# Generated by Django 5.0.4 on 2024-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation', models.DateField(auto_now_add=True)),
                ('Actualization', models.DateField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
                ('Service', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Icon', models.CharField(choices=[('lni-cog', 'Gear'), ('lni-stats-up', 'Graphic'), ('lni-users', 'Users'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=12)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
