# Generated by Django 5.0.4 on 2024-04-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Actualization',
            new_name='Modification',
        ),
    ]
